name: Update blog posts

on:
  schedule:
    - cron: '0 * * * *'
  workflow_dispatch:

jobs:
  update-readme-with-blog:
    name: Update this repo's README with latest blog posts

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: gautamkrishnar/blog-post-workflow@master
        with:
          committer_username: "utkarsh2102"
          committer_email: "guptautkarsh2102@gmail.com"
          feed_list: "https://utkarsh2102.com/index.xml"
